### ISSUE TITLE
The discord invite doesn't work and the linked "chaos" tag of stak overflow isn't actually about the language

### ISSUE THREAD

**Issue by ThePirate42** [chaos-lang/chaos#103]
This isn't exactly a bug, but it was the easiest way for me to contact you.

It seems that the discord invite in the community footer of the site doesn't work; more importantly, the the linked "chaos" tag of stak overflow isn't about the language, is about chaos teory. The link to stak overflow is erroneus, and **will** cause problems if chaos becomes more popular, so you should remove it ot replace it with a link to a tag that is really about your language as soon as possible.

**Comment by mertyildiran** [comment]
@ThePirate42 thank you so much for reporting these issues.

I guess the Discord invite is expired, I'll update the link as soon as possible.

While I have the privilege for creating tags on Stack Overflow, I need to ask a question about Chaos language on the website. Since I'm the author of this language, it would be inappropriate for me to ask a question on Stack Overflow about the language that I've created. Therefore somebody else should do it naturally on a later point. The Stack Overflow link is like a placeholder there right now. Also the context of the `chaos` tag might change in the future if the language becomes popular, who knows...

*Note: Please file the issues related to [chaos-lang.org](https://chaos-lang.org/) website into https://github.com/chaos-lang/chaos-lang.org repository.*
