### ISSUE TITLE
Lets print array by index

### ISSUE THREAD

**Issue by tankf33der** [chaos-lang/chaos#23]
Trivial code, first print works, second fails. Prints are equal in general.
```
array v = [1,22,333]
any i = v[0]
any j = v[i]
print j
print v[i]
```

```
$ chaos ./mik.e 
22
  Syntax error:        
    Module: ./mik.e     
    Line: 5            
    Cause: i           
```

**Comment by mertyildiran** [comment]
@tankf33der I'm grateful for your contributions. The issue fixed with https://github.com/chaos-lang/chaos/commit/af510a97c90f0bfbb9a23feb81e03627b4ca5d7d

The documentation website of the project is online: https://chaos-lang.org/

[Chaos C Extension Development](https://chaos-lang.org/docs/16_chaos_c_extensions_development) and the [API Reference](https://chaos-lang.org/docs/api) pages might be especially interesting for you, if you ever want to develop a Chaos C extension.

You might also want to contribute to the documentation of the language. If so, it's located in [this repository](https://github.com/chaos-lang/chaos-lang.org/tree/master/website/docs) now.
