### ISSUE TITLE
Documentation: MacOS build from source won't work with XCode toolchain

### ISSUE THREAD

**Issue by f00stx** [chaos-lang/chaos#40]
Installing from source on MacOS Catalina (other versions untested) seems to require that you manually add Homebrew's version of bison and flex to your path, and the appropriate LDFLAGS/CPPFLAGS etc, otherwise `make` fails. The XCode toolchain's version of bison fails with:

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bison: invalid option -- W`

Could the installation documentation be updated to reflect this? It's in the `brew` caveats but it's easy to miss if anyone just blasts through homebrew installs without reading them.

**Comment by mertyildiran** [comment]
@f00stx actually there is a [block of code](https://github.com/chaos-lang/chaos/blob/9a4f0c213bbb2c291cb99d065c0c10c60ef157a5/requirements.sh#L33-L39) to fix that issue. That block is called by `make requirements` command.

There are [automated tests](https://github.com/chaos-lang/chaos/blob/master/.github/workflows/tests.yml#L97-L135) for macOS and they run on [Catalina](https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md).

I'm not quite sure what went wrong on your machine. Is there a possibility that you did not run `make requirements`?

The only different thing in the tests is `mv /usr/local/bin/gcc-8 /usr/local/bin/gcc` line which makes `gcc` an actual GCC because by default on macOS `/usr/local/bin/gcc` is actually Clang. But it's unrelated to `bison`, I think.

There is also another make command for compiling the interpreter using Clang: `make clang`

**Comment by f00stx** [comment]
Ahh, I see - it appends to `.bash_profile` but I'm using zsh.

Possible to detect which shell a user is running and append to the appropriate file (`.zshrc` in my case)?

**Comment by mertyildiran** [comment]
@f00stx because there are shebangs `#!/bin/bash` in all Bash scripts and `SHELL=/bin/bash` in Makefile, the whole process should go through Bash. Probably `source ~/.bash_profile` has no effect or `.bash_profile` is not loaded into your shell session. If you look at the tests closely, you will see that I needed to use `source ~/.bash_profile` before every build command (`make` or `make clang`) [here](https://github.com/chaos-lang/chaos/blob/f61fc6677caf0b38858816fecf00dbbd54dbc60a/.github/workflows/tests.yml#L112) and [here](https://github.com/chaos-lang/chaos/blob/f61fc6677caf0b38858816fecf00dbbd54dbc60a/.github/workflows/tests.yml#L123).

Maybe we should write [these lines](https://github.com/chaos-lang/chaos/blob/9a4f0c213bbb2c291cb99d065c0c10c60ef157a5/requirements.sh#L36-L38) directly into `.bashrc` or `/etc/profile`. Could you please take a look at these solutions(or any alternative solution) and test them if they works?
