### ISSUE TITLE
[Bug] Loop scope issues. Is this intended behaviour?

### ISSUE THREAD

**Issue by Professor-Peanut** [chaos-lang/chaos#47]
Variables appear to become "invisible" within loop scopes such as "x times do ... end"
Here is an example:

```
num def check(num n)
	print n
	num p = n+1
	return p
end

void def test() 
	num x = 0
	INFINITE times do	
		num r = check(x)  // <- Can't see 'x'
	end
end 

test()
```

The error I'm getting is this:
`Chaos Error:                
    Module: test.kaos         
    Line: 4                   
    Undefined variable: x `

Is this behaviour intended? Why can't a loop "see" its surrounding function?
Please help!

**Comment by mertyildiran** [comment]
@StefanLaszlo it turns out I have to make `executed_function` ([used in here](https://github.com/chaos-lang/chaos/blob/58fc6be01221f52261e489dc3fce1d88321dfcfa/symbol.c#L1110)) a stack just like `module_path_stack` or `complex_mode_stack`. It will take quite a long time and I'm really exhausted from dealing with all of the problems in this language just by myself. Would you like to give some help?

**Comment by mertyildiran** [comment]
@Professor-Peanut fixed with https://github.com/chaos-lang/chaos/commit/12ccda03929a93d88628e1a37b5c43a778867590
