### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by zethra** [chaos-lang/chaos#75]
I've made an AUR package for chaos. https://aur.archlinux.org/packages/chaos/
If you want to maintain it instead let me know and I'll transfer ownership.

**Comment by mertyildiran** [comment]
@zethra thank you so much for creating this package. Feel free to maintain it.

Could you please also create packages for other distros that you're familiar with. For example: DEB (Debian/Ubuntu), RPM (CentOS/RHEL & Fedora) etc. I would be much appreciated if you can do that. I'm not so experienced in creating packages.

I've also invited you to the [GitHub organization](https://github.com/chaos-lang). Feel free to open PRs or create new repositories related to software packaging or any other development related to Chaos language.

**Comment by zethra** [comment]
Thanks for the invite! Not sure how qualified I am but I'll do what I can 😅. Unfortunately I'm not very experience packaging for other distros.  I might be able to work up an rpm and and a deb but I'm not sure where to publish them.  Especially for debs.

**Comment by zethra** [comment]
I'm currently in the process of trying to glue the Rust regex library to chaos 😅.

**Comment by mertyildiran** [comment]
@zethra Thank you so much for accepting the invite.

OK then I'm closing this issue. We can work on the packaging and distribution possibilities in the future.

I'm not sure how possible it's to create an FFI for Rust at this state because everything revolves around C language. I'm not a Rust developer. As far as I understand you'll develop the core Chaos library for regex functionality with [this repository](https://github.com/zethra/chaos-regex) of yours. Feel free to move it to the [GitHub organization](https://github.com/chaos-lang) since we host the core libraries(official spells) under the organization. Renaming it to `re` or `regex` would be more appropriate since we inspire from [Python's core modules](https://docs.python.org/3/py-modindex.html).
